menu:
#- {name: 'people', url: '/people'}
#- {name: 'publications', url: '/publications'}
#- {name: 'courses', url: '/courses'}
- name: 'C.V.'
  name_pt: 'C.V.'
  url: '/cv'
- name: 'Contact'
  name_pt: 'Contato'
  url: '/contact'

#people:
#- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
#- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
#- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

#courses:
#- {name: 'Vector Calculus', url: 'vector-calculus'}
#- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
#- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/cavalcantialex'}
- {icon: 'twitter', link: 'https://twitter.com/cavalcantialexs'}
- {icon: 'google-scholar', link: 'https://scholar.google.com/citations?user=MqC5xfEAAAAJ&hl=en'}

contacts:
- name: 'Alexsandra Cavalcanti'
  title: 'Ph.D. Student'
  title_pt: 'Doutoranda'
  department: 'Political Science'
  department_pt: 'Ciência Política'
  institution: 'University of Rochester'
  institution_pt: 'Universidade de Rochester'
  institution_address: 'Harkness Hall, Rochester-NY'
  email: 'acavalca@ur.rochester.edu'
  image: 'assets/img/contact.jpeg'
